clusters:
  - name: dev
    environment: development
    kargoStage: dev
  - name: pro
    environment: production
    kargoStage: pro
  - name: lelo
    environment: lelo
    kargoStage: lelo
  - name: pro-v2
    environment: production
    kargoStage: pro-v2