# OpenEBS
localpv-provisioner:
  enabled: true

  hostpathClass:
    enabled: true
    name: openebs-hostpath
    isDefaultClass: false
    reclaimPolicy: Delete
    basePath: /var/openebs/local

# No necesitamos almacenamiento replicado de Mayastor
engines:
  replicated:
    mayastor:
      enabled: false