nodeExporter:
  enabled: false

grafana:
  sidecar:
    skipTlsVerify: true
  enabled: true
  ingress:
    enabled: true
    ingressClassName: public
    hosts:
      - grafana.internal
    annotations:
      nginx.ingress.kubernetes.io/rewrite-target: /
    path: /
    pathType: Prefix
  adminPassword: admin  # ponlo en un Secret en producción
  persistence:
    enabled: true
    storageClassName: microk8s-hostpath
    accessModes: [ "ReadWriteOnce" ]
    size: 5Gi
  initChownData:
    enabled: false
  additionalDataSources:
    - name: Loki
      type: loki
      uid: loki-datasource
      url: http://loki.loki.svc.cluster.local:3100/
      access: proxy
      isDefault: false


prometheus:
  ingress:
    enabled: true
    ingressClassName: public
    hosts:
      - prometheus.internal
    paths:
      - /
    pathType: Prefix

  prometheusSpec:
    enableRemoteWriteReceiver: true

    scrapeClasses:
      - default: true
        name: cluster-relabeling
        relabelings:
          - sourceLabels: [ __name__ ]
            regex: (.*)
            targetLabel: cluster
            replacement: core
            action: replace

    serviceMonitorSelectorNilUsesHelmValues: false
    podMonitorSelectorNilUsesHelmValues: false
    retention: 7d

    storageSpec:
      volumeClaimTemplate:
        spec:
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 10Gi
          storageClassName: "microk8s-hostpath"

alertmanager:
  alertmanagerSpec:
    storage:
      volumeClaimTemplate:
        spec:
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 2Gi
          storageClassName: "microk8s-hostpath"
