# Desplegar Promtail
tolerations:
  - operator: Exists

podAnnotations:
  prometheus.io/scrape: "true"
  prometheus.io/port: "http-metrics"

config:
  clients:
    - url: http://loki.loki.svc.cluster.local:3100/loki/api/v1/push

#  snippets:
#    scrapeConfigs: |
#      - job_name: kubernetes-pods
#        kubernetes_sd_configs:
#          - role: pod
#        relabel_configs:
#          - source_labels: [__meta_kubernetes_pod_label_name]
#            target_label: __service__
#          - source_labels: [__meta_kubernetes_namespace]
#            target_label: namespace
#          - source_labels: [__meta_kubernetes_pod_name]
#            target_label: pod
#          - action: replace
#            source_labels: [__meta_kubernetes_pod_node_name]
#            target_label: node
#          - action: drop
#            regex: ""
#            source_labels: [__meta_kubernetes_pod_container_name]
#        pipeline_stages:
#          - docker: {}
#        static_configs:
#          - targets:
#              - localhost
#            labels:
#              job: varlogs
#              __path__: /var/log/pods/*/*/*.log
