apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: calibre-web
  annotations:
    {{- range $key, $value := .Values.ingress.annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  rules:
    - host: {{ .Values.ingress.hostname }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: calibre-web
                port:
                  number: {{ .Values.service.port }}
    {{- if .Values.externalAccess.enabled }}
    - host: {{ .Values.externalAccess.hostname }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: calibre-web
                port:
                  number: {{ .Values.service.port }}
    {{- end }}
  {{- if .Values.ingress.tls }}
  tls:
    {{- range .Values.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
    {{- if .Values.externalAccess.enabled }}
    - hosts:
        - {{ .Values.externalAccess.hostname }}
      secretName: {{ .Values.externalAccess.tlsSecretName }}
    {{- end }}
  {{- end }}
