vault:
  server: http://vault.vault.svc.cluster.local:8200
  auth:
    appRole:
      roleId: 4a8f946b-b7d8-e510-a7da-33e9eff33bfb
      secretRef:
        name: vault-approle-secret
        key: secret-id
        namespace: default
  caProvider:
    name: home-internal-root-ca