certificates:
  - name: home-assistant-dev
    namespace: home-assistant
    duration: 8760h
    renewBefore: 720h
    domain: internal.org
  - name: jellyfin
    namespace: jellyfin
    duration: 8760h
    renewBefore: 720h
letsEncrypt:
  enable: true
  issuerName: letsencrypt-production
  server: https://acme-v02.api.letsencrypt.org/directory
  namespaces:
    - home-assistant
    - jellyfin