apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: loki-external-secret
  namespace: loki
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: vault-store
    kind: ClusterSecretStore
  target:
    name: loki
    template:
      type: Opaque
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: loki
        decodingStrategy: Auto