apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "adguard-home.fullname" . }}
  labels:
    app: {{ include "adguard-home.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "adguard-home.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "adguard-home.name" . }}
    spec:
      hostNetwork: {{ .Values.hostNetwork }}
      dnsPolicy: {{ ternary "ClusterFirstWithHostNet" "ClusterFirst" .Values.hostNetwork }}
      containers:
        - name: adguard-home
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- with .Values.service.ports }}
          ports:
            {{- toYaml . | nindent 12 }}
            {{- if $.Values.metalLb.enabled }}
            {{- toYaml $.Values.metalLb.ports | nindent 12 }}
            {{- end }}
          {{- end }}
          volumeMounts:
            - mountPath: {{ .Values.persistence.confMountPath }}
              name: conf
            - mountPath: {{ .Values.persistence.workMountPath }}
              name: work
      volumes:
        - name: conf
          hostPath:
            path: {{ .Values.persistence.confPath }}
            type: Directory
        - name: work
          hostPath:
            path: {{ .Values.persistence.workPath }}
            type: Directory