apiVersion: v1
kind: Service
metadata:
  name: {{ include "adguard-home.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ include "adguard-home.name" . }}
  {{- with .Values.service.ports }}
  ports:
  {{- range . }}
    - port: {{ .containerPort }}
      targetPort: {{ .containerPort }}
      protocol: {{ .protocol }}
      name: {{ .name }}
  {{- end }}
  {{- end }}
---
{{- if .Values.metalLb.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: adguard-home-dns
spec:
  type: LoadBalancer
  loadBalancerIP: {{ .Values.metalLb.ip }}
  externalTrafficPolicy: Local
  selector:
    app: adguard-home
  ports:
    - name: dns-tcp
      port: 53
      targetPort: 53
      protocol: TCP
    - name: dns-udp
      port: 53
      targetPort: 53
      protocol: UDP
{{- end }}