ingress:
  annotations:
    cert-manager.io/cluster-issuer: home-internal-ca-issuer
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
  tls:
    - hosts:
        - warracker-dev.internal
      secretName: warracker-dev-internal-tls