persistence:
  media:
    enabled: true
    type: hostPath
    hostPath: /mnt/services/media
  cache:
    enabled: true
    type: hostPath
    hostPath: /mnt/services/jellyfin/cache

resources:
  requests:
    cpu: "50m"
    memory: "64Mi"
  limits:
    cpu: "1500m"
    memory: "2Gi"

livenessProbe:
  httpGet:
    path: /health
    port: http
  initialDelaySeconds: 90
  periodSeconds: 30
  timeoutSeconds: 10
  failureThreshold: 5

readinessProbe:
  httpGet:
    path: /health
    port: http
  initialDelaySeconds: 30
  periodSeconds: 10