deploymentMode: SingleBinary

loki:
  auth_enabled: false
  limits_config:
    reject_old_samples: false
  useTestSchema: true
  storage:
    type: filesystem

singleBinary:
  replicas: 2
  autoscaling:
    enabled: true
  persistence:
    storageClass: microk8s-hostpath

chunksCache:
  enabled: false

write:
  replicas: 0
read:
  replicas: 0
backend:
  replicas: 0
#ingester:
#  replicas: 0
#distributor:
#  replicas: 0
#querier:
#  replicas: 0