loki:
  enabled: true
  isDefault: true
  commonConfig:
    replication_factor: 1
  storage:
    type: filesystem
  persistence:
    enabled: true
    accessModes:
      - ReadWriteOnce
    size: 10Gi
    storageClassName: microk8s-hostpath
  auth_enabled: false

  # recursos (opcional)
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 256Mi

  config: |-
    schema_config:
      configs:
        - from: 2024-01-01
          store: boltdb-shipper
          object_store: filesystem
          schema: v11
          index:
            prefix: index_
            period: 24h
    storage_config:
      boltdb_shipper:
        active_index_directory: /loki/index
        cache_location: /loki/cache
        shared_store: filesystem
      filesystem:
        directory: /loki/chunks
    limits_config:
      reject_old_samples: false
    ruler:
      storage:
        type: local
        local:
          directory: /loki/rules
      rule_path: /loki/rules-temp
      alertmanager_url: http://kube-prometheus-stack-alertmanager.kube-prometheus-stack:9093
    server:
      http_listen_port: 3100
    table_manager:
      retention_deletes_enabled: true
      retention_period: 168h  # 7 días en horas
