deploymentMode: SingleBinary

loki:
  auth_enabled: false
  limits_config:
    reject_old_samples: false
  useTestSchema: true
  storage:
    type: filesystem

singleBinary:
#  replicas: 1
#  autoscaling:
#    enabled: true
  persistence:
    storageClass: microk8s-hostpath