replicaCount: 1

image:
  repository: grafana/loki
  tag: "2.8.2"  # o la versión que prefieras
  pullPolicy: IfNotPresent

loki:
  config:
    auth_enabled: false

    server:
      http_listen_port: 3100

    ingester:
      lifecycler:
        address: 127.0.0.1
        ring:
          kvstore:
            store: inmemory
          replication_factor: 1
      chunk_idle_period: 5m
      chunk_retain_period: 30s
      max_transfer_retries: 0

    schema_config:
      configs:
        - from: 2020-10-24
          store: boltdb
          object_store: filesystem
          schema: v11
          index:
            prefix: index_
            period: 168h

    storage_config:
      filesystem:
        directory: /data/loki

    limits_config:
      enforce_metric_name: false
      reject_old_samples: true
      reject_old_samples_max_age: 168h

    chunk_store_config:
      max_look_back_period: 0s

    table_manager:
      retention_deletes_enabled: false
      retention_period: 0s

persistence:
  enabled: true
  accessModes:
    - ReadWriteOnce
  size: 10Gi

service:
  type: ClusterIP
  port: 3100

resources: {}

