deploymentMode: SingleBinary

loki:
  auth_enabled: false
  limits_config:
    reject_old_samples: false
  useTestSchema: true
  storage:
    type: s3
    bucketNames:
      chunks: loki
      ruler: loki
      admin: loki
    s3:
      s3: loki
      endpoint: minio.internal:9000
      accessKeyId: uXY6lTBIb627G3WPgtJ9
      secretAccessKey: fujNdS9qUbz42mjEZjK4gXPYiuI5IRdi5RbFf7uP
      insecure: true
      s3ForcePathStyle: true

chunksCache:
  enabled: false

singleBinary:
  enabled: true
  autoscaling:
    enabled: true
    minReplicas: 2
  persistence:
    storageClass: microk8s-hostpath

write:
  replicas: 0
read:
  replicas: 0
backend:
  replicas: 0
#ingester:
#  replicas: 0
#distributor:
#  replicas: 0
#querier:
#  replicas: 0