
loki:
  auth_enabled: false
  limits_config:
    reject_old_samples: false
  useTestSchema: true
  storage:
    type: s3
    s3:
      s3: loki
      endpoint: minio.internal:9000
      accessKeyId: uXY6lTBIb627G3WPgtJ9
      secretAccessKey: fujNdS9qUbz42mjEZjK4gXPYiuI5IRdi5RbFf7uP
      insecure: true
      s3forcepathstyle: true

write:
  persistence:
    storageClass: microk8s-hostpath
read:
  persistence:
    storageClass: microk8s-hostpath
backend:
  persistence:
    storageClass: microk8s-hostpath