deploymentMode: SingleBinary

loki:
  auth_enabled: false
  limits_config:
    reject_old_samples: false
  useTestSchema: true
  commonConfig:
    replication_factor: 1
  storage:
    type: s3
    bucketNames:
      chunks: loki
      ruler: loki
      admin: loki
    s3:
      s3: loki
      endpoint: minio.internal:9000
      accessKeyId: uXY6lTBIb627G3WPgtJ9
      secretAccessKey: fujNdS9qUbz42mjEZjK4gXPYiuI5IRdi5RbFf7uP
      insecure: true
      s3ForcePathStyle: true
  storage_config:
    tsdb_shipper:
      active_index_directory: /loki/index
      cache_location: /loki/index_cache
    aws:
      s3: s3://uXY6lTBIb627G3WPgtJ9:fujNdS9qUbz42mjEZjK4gXPYiuI5IRdi5RbFf7uP@minio.internal:9000/loki
      s3forcepathstyle: true

chunksCache:
  enabled: false

singleBinary:
  enabled: true
  autoscaling:
    enabled: true
  persistence:
    storageClass: microk8s-hostpath

write:
  replicas: 0
read:
  replicas: 0
backend:
  replicas: 0
#ingester:
#  replicas: 0
#distributor:
#  replicas: 0
#querier:
#  replicas: 0