{{- range $extSecret := .Values.extSecrets }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: kargo-{{ $extSecret.name }}
  namespace: {{ $extSecret.namespace }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-store
    kind: ClusterSecretStore
  target:
    name: kargo-{{ $extSecret.name }}
    creationPolicy: Owner
    template:
      type: {{ $extSecret.templateType | default "Opaque" }}
  data:
    {{- range $secret := $extSecret.secrets }}
    - secretKey: {{ $secret.secretKey }}
      remoteRef:
        key: {{ $secret.remoteRef.key }}
        property: {{ $secret.remoteRef.property | default $secret.secretKey }}
    {{- end }}
---
{{- end }}