ingress:
  hosts:
    - host: immich-dev.internal
      paths:
        - path: /
          pathType: Prefix

postgresql:
  auth:
    existingSecret: immich-postgresql-auth

externalSecrets:
  enabled: true
  secretStoreRef:
    name: vault-store
    kind: ClusterSecretStore
valkey:
  external:
    existingSecret: immich-valkey-auth