ingress:
  hosts:
    - host: immich-dev.internal
      paths:
        - path: /
          pathType: Prefix

postgresql:
  auth:
    existingSecret: immich-postgresql-auth

#externalSecrets:
#  enabled: true
#  secretStoreRef:
#    name: vault-store
#    kind: ClusterSecretStore
valkey:
  auth:
    existingSecret: immich-valkey-auth
#  external:
#    existingSecret: immich-valkey-auth

extraVolumes:
  - name: trusted-ca
    secret:
      secretName: immich-trusted-ca

extraVolumeMounts:
  - name: trusted-ca
    mountPath: /etc/trusted-ca
    readOnly: true

server:
  env:
    - name: NODE_EXTRA_CA_CERTS
      value: /etc/trusted-ca/tls.crt