dashboard:
  enabled: true

  service:
    type: ClusterIP
    port: 3100

  ingress:
    enabled: true
    annotations: {}
    hosts:
      - host: rollouts.internal
        paths:
          - /
    tls: []
