fullnameOverride: calibre-web

image:
  repository: docker.io/linuxserver/calibre-web

containerPort: 8083

env:
  - name: PUID
    value: "1000"   # UID del usuario en Lima
  - name: PGID
    value: "1000"   # GID del usuario en Lima
  - name: TZ
    value: "Europe/Madrid"

ingress:
  enabled: true

resources:
  requests:
    cpu: "50m"
    memory: "64Mi"
  limits:
    cpu: "1000m"
    memory: "1Gi"