image:
  repository: docker.io/linuxserver/calibre-
deployment:
  additionalEnv:
    - name: PUID
      value: "1000"
    - name: PGID
      value: "1000"
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 256Mi