certificates:
  - name: vault
    namespace: vault
    duration: 8760h
    renewBefore: 720h
  - name: grafana
    namespace: kube-prometheus-stack
    duration: 8760h
letsEncrypt:
  enable: true
  issuerName: letsencrypt-production
  server: https://acme-v02.api.letsencrypt.org/directory
  namespaces:
    - argocd
    - kargo
    - vault