server:
  ingress:
    enabled: true
    ingressClassName: nginx
    hosts:
      - auth-dev.internal
#    paths:
#      - path: /
#        pathType: Prefix
    tls:
      - secretName: auth-dev-tls
        hosts:
          - auth-dev.internal

  envFrom:
    - secretRef:
        name: authentik-env
    - secretRef:
        name: authentik-postgres

authentik:
  postgresql:
    enabled: false
    host: authentik-db-rw.authentik.svc.cluster.local
    port: 5432
    name: authentik
    user: authentik
    password: # lo recomendable aquí es usar un Secret
      existingSecret: authentik-db-secret
      existingSecretPasswordKey: password

worker:
  envFrom:
    - secretRef:
        name: authentik-env

redis:
  enabled: true

postgresql:
  enabled: false

certManager:
  enabled: true
  clusterIssuerName: home-internal-ca-issuer
