server:
  ingress:
    enabled: true
    ingressClassName: nginx
    hosts:
      - host: auth-dev.internal
        paths:
          - path: /
            pathType: Prefix
    tls:
      - secretName: auth-dev-tls
        hosts:
          - auth-dev.internal

  envFrom:
    - secretRef:
        name: authentik-env
    - secretRef:
        name: authentik-postgres

  env:
    AUTHENTIK_POSTGRESQL__HOST: authentik-db-rw.authentik.svc
    AUTHENTIK_POSTGRESQL__PORT: "5432"
    AUTHENTIK_POSTGRESQL__NAME: authentik

redis:
  enabled: true

postgresql:
  enabled: false

certManager:
  enabled: true
  clusterIssuerName: home-internal-ca-issuer
