server:
  ingress:
    enabled: true
    ingressClassName: nginx
    hosts:
      - host: auth-dev.internal
        paths:
          - path: /
            pathType: Prefix
    tls:
      - secretName: auth-dev-tls
        hosts:
          - auth-dev.internal

  envFrom:
    - secretRef:
        name: authentik-env
    - secretRef:
        name: authentik-postgres

  env:
    - name: AUTHENTIK_POSTGRESQL__HOST
      value: authentik-db-rw.authentik.svc
    - name: AUTHENTIK_POSTGRESQL__PORT
      value: "5432"
    - name: AUTHENTIK_POSTGRESQL__NAME
      value: authentik


redis:
  enabled: true

postgresql:
  enabled: false

certManager:
  enabled: true
  clusterIssuerName: home-internal-ca-issuer
