postgresql:
  enabled: false

redis:
  enabled: false

authentik:
  postgresql:
    # -- set the postgresql hostname to talk to
    # if unset and .Values.postgresql.enabled == true, will generate the default
    # @default -- `{{ .Release.Name }}-postgresql`
    host: "authentik-postgres"
    # -- postgresql Database name
    # @default -- `authentik`
    name: "authentik"
    # -- postgresql Username
    # @default -- `authentik`
#    user: "authentik"
#    password: "authentik"
    port: 5432
  redis:
    # -- set the redis hostname to talk to
    # @default -- `{{ .Release.Name }}-redis-master`
    host: "authentik-redis"
    password: ""

server:
  ingress:
    enabled: true
    ingressClassName: nginx
