zigbee2mqtt:
  mqtt:
    server: "mqtt://mosquitto.home-assistant.svc.cluster.local:1883"
  serial:
    adapter: "fake"
ingress:
  hosts:
    - host: zigbee2mqtt-dev.internal
      paths:
        - path: /
          pathType: Prefix