zigbee2mqtt:
  serial:
    port: "null"
ingress:
  hosts:
    - host: zigbee2mqtt-dev.internal
      paths:
        - path: /
          pathType: Prefix

statefulset:
  resources:
    requests:
      memory: 200Mi
      cpu: 75m
    limits:
      memory: 200Mi
      cpu: 75m