api:
  host: kargo.internal
  secret:
    name: kargo-api
  service:
    type: NodePort
  ingress:
    enabled: true
    annotations:
      nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
      nginx.ingress.kubernetes.io/ssl-redirect: "443"
      cert-manager.io/cluster-issuer: home-internal-ca-issuer
      nginx.ingress.kubernetes.io/ssl-passthrough: "true"
    ingressClassName: nginx
    tls:
      selfSignedCert: false
