api:
  host: kargo.internal
  secret:
    name: kargo-api
  service:
    type: ClusterIP
  ingress:
    enabled: true
    ingressClassName: nginx
  tls:
    enabled: false
    selfSignedCert: true
    secretName: kargo-api-tls
    hosts:
      - kargo.internal
