apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: argocd-dev-cluster
  namespace: argocd
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: vault-store
    kind: ClusterSecretStore
  target:
    name: argocd-cluster-dev-secret
    template:
      type: Opaque
      metadata:
        labels:
          app.kubernetes.io/part-of: argocd
          argocd.argoproj.io/secret-type: cluster
          argocd.argoproj.io/auto-label-cluster-info: "true"
          name: dev
          environment: dev
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: argocd/clusters/dev
        decodingStrategy: Auto
---