{{- range $cluster := .Values.clusters }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: argocd-{{ $cluster.name }}-cluster
  namespace: argocd
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: vault-store
    kind: ClusterSecretStore
  target:
    name: argocd-cluster-{{ $cluster.name }}-secret
    template:
      type: Opaque
      metadata:
        labels:
          app.kubernetes.io/part-of: argocd
          argocd.argoproj.io/secret-type: cluster
          argocd.argoproj.io/auto-label-cluster-info: "true"
          name: {{ $cluster.name }}
          environment: {{ $cluster.environment }}
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: argocd/clusters/{{ $cluster.name }}
        decodingStrategy: Auto
---
{{- end }}