apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: home-root
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Squallium/kubernetes-at-home.git
    targetRevision: main
    path: gitops
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
