auth:
  openid:
    enabled: true
    providerName: authentik
    authurl: https://auth.internal.org/application/o/vikunja/

ingress:
  host: vikunja.internal

deployment:
  resources:
    requests:
      cpu: 250m
      memory: 256Mi
    limits:
      cpu: 1
      memory: 1Gi
