apiVersion: v1
kind: ConfigMap
metadata:
  name: vikunja-config
data:
  VIKUNJA_DATABASE_TYPE: postgres
  VIKUNJA_DATABASE_HOST: vikunja-postgres
  VIKUNJA_DATABASE_USER: vikunja
  VIKUNJA_DATABASE_PASSWORD: vikunja
  VIKUNJA_DATABASE_DATABASE: vikunja
  VIKUNJA_TYPESENSE_HOST: vikunja-typesense
  VIKUNJA_TYPESENSE_PORT: "8108"
  VIKUNJA_TYPESENSE_APIKEY: vikunja
  VIKUNJA_SERVICE_JWTSECRET: {{ .Values.jwtSecret }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: vikunja-config-file
data:
  config.yml: |
{{- if .Values.auth.openid.enabled }}
    auth:
      openid_connect:
        enabled: true
        providers:
          - name: {{ default "authentik" .Values.auth.openid.providerName }}
            authurl: {{ .Values.auth.openid.authurl | quote }}
            clientid: {{ .Values.auth.openid.client_id | quote }}
            clientsecret: {{ .Values.auth.openid.client_secret | quote }}
            scope: openid profile email
            forceuserinfo: false
{{- end }}
