apiVersion: apps/v1
kind: Deployment
metadata:
  name: vikunja
  labels:
    app: vikunja
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vikunja
  template:
    metadata:
      labels:
        app: vikunja
    spec:
      containers:
        - name: vikunja
          image: {{ .Values.vikunja.image }}
          ports:
            - containerPort: 3456
          envFrom:
            - configMapRef:
                name: vikunja-config
