{{/*apiVersion: networking.k8s.io/v1*/}}
{{/*kind: Ingress*/}}
{{/*metadata:*/}}
{{/*  name: prowlarr*/}}
{{/*  annotations:*/}}
{{/*    {{- range $key, $value := .Values.ingress.annotations }}*/}}
{{/*    {{ $key }}: {{ $value | quote }}*/}}
{{/*    {{- end }}*/}}
{{/*spec:*/}}
{{/*  rules:*/}}
{{/*    - host: prowlarr-dev.internal*/}}
{{/*      http:*/}}
{{/*        paths:*/}}
{{/*          - path: /*/}}
{{/*            pathType: Prefix*/}}
{{/*            backend:*/}}
{{/*              service:*/}}
{{/*                name: prowlarr*/}}
{{/*                port:*/}}
{{/*                  number: 80*/}}
{{/*  {{- if .Values.ingress.tls }}*/}}
{{/*  tls:*/}}
{{/*    {{- range .Values.ingress.tls }}*/}}
{{/*    - hosts:*/}}
{{/*        {{- range .hosts }}*/}}
{{/*        - {{ . }}*/}}
{{/*        {{- end }}*/}}
{{/*      secretName: {{ .secretName }}*/}}
{{/*    {{- end }}*/}}
{{/*  {{- end }}*/}}