apiVersion: v1
kind: Service
metadata:
  name: vikunja-postgres
  labels:
    app: vikunja-postgres
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.postgresql.port }}
      targetPort: {{ .Values.postgresql.port }}
  selector:
    app: vikunja-postgres
