apiVersion: apps/v1
kind: Deployment
metadata:
  name: vikunja-postgres
  labels:
    app: vikunja-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vikunja-postgres
  template:
    metadata:
      labels:
        app: vikunja-postgres
    spec:
      containers:
        - name: postgres
          image: {{ .Values.postgresql.image }}
          ports:
            - containerPort: {{ .Values.postgresql.port }}
          env:
            - name: POSTGRES_USER
              value: {{ .Values.postgresql.username }}
            - name: POSTGRES_PASSWORD
              value: {{ .Values.postgresql.password }}
            - name: POSTGRES_DB
              value: {{ .Values.postgresql.database }}
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-data
          emptyDir: {}   # lo cambiaremos por PVC luego
