apiVersion: apps/v1
kind: Deployment
metadata:
  name: warracker
spec:
  replicas: {{ .Values.warracker.replicas }}
  selector:
    matchLabels:
      app: warracker
  template:
    metadata:
      labels:
        app: warracker
    spec:
      containers:
        - name: warracker
          image: {{ .Values.warracker.image }}
          ports:
            - containerPort: {{ .Values.warracker.containerPort }}
          env:
            - name: DB_HOST
              value: {{ .Values.postgres.host | default "warracker-postgres" }}
            - name: DB_PORT
              value: "{{ .Values.postgres.servicePort }}"
            - name: DB_NAME
              value: {{ .Values.postgres.database }}
            - name: DB_USER
              value: {{ .Values.postgres.user }}
            - name: DB_PASSWORD
              value: {{ .Values.postgres.password }}
            {{- range $key, $value := .Values.warracker.additionalEnv }}
            - name: {{ $key }}
              value: "{{ $value }}"
            {{- end }}
          volumeMounts:
            - mountPath: /data/uploads
              name: uploads-storage
      volumes:
        - name: uploads-storage
          persistentVolumeClaim:
            claimName: warracker-uploads-pvc
