apiVersion: apps/v1
kind: Deployment
metadata:
  name: warracker
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
      app: warracker
  template:
    metadata:
      labels:
        app: warracker
    spec:
      containers:
        - name: warracker
          image: {{ .Values.deployment.image }}
          ports:
            - containerPort: {{ .Values.deployment.containerPort }}
          env:
            - name: DB_HOST
              value: {{ .Values.postgresql.host | default "warracker-postgres" }}
            - name: DB_PORT
              value: "{{ .Values.postgresql.servicePort }}"
            - name: DB_NAME
              value: {{ .Values.postgresql.database }}
            - name: DB_USER
              value: {{ .Values.postgresql.user }}
            - name: DB_PASSWORD
              value: {{ .Values.postgresql.password }}
            {{- range $key, $value := .Values.deployment.additionalEnv }}
            - name: {{ $key }}
              value: "{{ $value }}"
            {{- end }}
          volumeMounts:
            - mountPath: /data/uploads
              name: uploads-storage
            - name: trusted-ca
              mountPath: /usr/local/share/ca-certificates/root-ca.crt
              subPath: tls.crt
          resources:
            {{- toYaml .Values.deployment.resources | nindent 12 }}
          command: [ "/bin/sh", "-c" ]
          args:
            - update-ca-certificates && exec /usr/bin/supervisord -c /etc/supervisor/conf.d/supervisord.conf
      volumes:
        - name: uploads-storage
          persistentVolumeClaim:
            claimName: warracker-uploads-pvc
        - name: trusted-ca
          secret:
            secretName: warracker-trusted-ca
