apiVersion: apps/v1
kind: Deployment
metadata:
  name: warracker-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: warracker-postgres
  template:
    metadata:
      labels:
        app: warracker-postgres
    spec:
      containers:
        - name: postgres
          image: {{ .Values.postgresql.image }}
          ports:
            - containerPort: {{ .Values.postgresql.port }}
          env:
            - name: POSTGRES_USER
              value: {{ .Values.postgresql.username | quote }}
            - name: POSTGRES_PASSWORD
              value: {{ .Values.postgresql.password | quote }}
            - name: POSTGRES_DB
              value: {{ .Values.postgresql.database | quote }}
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
          {{- include "chart.resources" (dict "name" "postgresql" "Values" .Values) | nindent 10 }}
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: warracker-postgres-pvc
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: warracker-postgres-pv
spec:
  capacity:
    storage: {{ .Values.postgresql.storage | default "5Gi" }}
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: {{ .Values.postgresql.storagePath }}
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: warracker-postgres-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  resources:
    requests:
      storage: {{ .Values.postgresql.storage | default "5Gi" }}
---
apiVersion: v1
kind: Service
metadata:
  name: warracker-postgres
  labels:
    app: warracker-postgres
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.postgresql.port }}
      targetPort: {{ .Values.postgresql.port }}
  selector:
    app: warracker-postgres
