apiVersion: apps/v1
kind: Deployment
metadata:
  name: warracker-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: warracker-postgres
  template:
    metadata:
      labels:
        app: warracker-postgres
    spec:
      containers:
        - name: postgres
          image: {{ .Values.postgres.image }}
          ports:
            - containerPort: {{ .Values.postgres.servicePort }}
          env:
            - name: POSTGRES_USER
              value: {{ .Values.postgres.user | quote }}
            - name: POSTGRES_PASSWORD
              value: {{ .Values.postgres.password | quote }}
            - name: POSTGRES_DB
              value: {{ .Values.postgres.database | quote }}
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgres-storage
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: warracker-postgres-pvc
