apiVersion: v1
kind: Service
metadata:
  name: warracker-postgres
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.postgres.servicePort }}
      targetPort: {{ .Values.postgres.servicePort }}
  selector:
    app: warracker-postgres
