image:
  tag: 0.6.27
deployment:
  additionalVolumeMounts:
    - name: books
      mountPath: /books
  additionalVolumes:
    - name: books
      hostPathPath: /mnt/services/media/books
ingress:
  hostname: calibre-web-dev.thejedisway.com
