server:
  persistence:
    enabled: true
    useExistingPersistentVolume: true
    storageClass: manual
    hostPath: /mnt/services/media/fotos

ingress:
  enabled: true

podSecurityContext:
  seccompProfile:
    type: RuntimeDefault
  fsGroup: 1000

securityContext:
  allowPrivilegeEscalation: false
  runAsUser: 1000
  runAsGroup: 1000
  capabilities:
    drop:
      - ALL

resources:
  requests:
    cpu: 100m
    memory: 512Mi
  limits:
    cpu: 1
    memory: 2Gi

machineLearning:
  resources:
    requests:
      cpu: 100m
      memory: 512Mi
    limits:
      cpu: 1
      memory: 2Gi

postgresql:
  primary:
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        cpu: 1
        memory: 1Gi

valkey:
  primary:
    resources:
      requests:
        cpu: 50m
        memory: 64Mi
      limits:
        cpu: 500m
        memory: 512Mi