apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: romm-db
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: vault-store
    kind: ClusterSecretStore
  target:
    name: romm-db
    creationPolicy: Owner
    template:
      type: Opaque
  data:
    - secretKey: DB_USER
      remoteRef:
        key: {{ .Values.envSecretKeys.mariadb }}
        property: username
    - secretKey: DB_PASSWD
      remoteRef:
        key: {{ .Values.envSecretKeys.mariadb }}
        property: password
    - secretKey: DB_ROOT_PASSWD
      remoteRef:
        key: {{ .Values.envSecretKeys.mariadb }}
        property: root_password
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: romm-config
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: vault-store
    kind: ClusterSecretStore
  target:
    name: romm-config
    creationPolicy: Owner
    template:
      type: Opaque
  data:
    - secretKey: ROMM_AUTH_SECRET_KEY
      remoteRef:
        key: {{ .Values.envSecretKeys.config }}
        property: romm_auth_secret_key
    - secretKey: SCREENSCRAPER_USER
      remoteRef:
          key: {{ .Values.envSecretKeys.config }}
          property: screenscraper_user
    - secretKey: SCREENSCRAPER_PASSWORD
      remoteRef:
          key: {{ .Values.envSecretKeys.config }}
          property: screenscraper_password
    - secretKey: RETROACHIEVEMENTS_API_KEY
      remoteRef:
          key: {{ .Values.envSecretKeys.config }}
          property: retroachievements_api_key
