vikunja:
  image: vikunja/vikunja:0.24.6
  jwtSecret: supersecreto # cámbialo luego en serio

  ingress:
    enabled: true
    host: vikunja-dev.internal
    annotations: {}
    tls: []

postgresql:
  image: postgres:17.3
  username: vikunja
  password: vikunja
  database: vikunja
  port: 5432
  storage:
    enabled: false
    size: 1Gi

typesense:
  image: typesense/typesense:27.1
  apiKey: vikunja
  port: 8108
