image: vikunja/vikunja:2.7.0
secret: supersecreto # cámbialo luego en serio
publicUrl: https://vikunja.internal

auth:
  openid:
    enabled: false

deployment:
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 512Mi

ingress:
  enabled: true
  host: placeholder
  annotations: {}
  tls: []

storagePath:
  files: /mnt/services/vikunja/files

postgresql:
  image: paradedb:0.26.0
  username: vikunja
  password: vikunja
  database: vikunja
  storage: 1Gi
  port: 5432
