apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: vault-store
  namespace: default
spec:
  provider:
    vault:
      server: http://vault.vault.svc.cluster.local:8200
      path: secret
      version: v2
      auth:
        # VaultAppRole authenticates with Vault using the
        # App Role auth mechanism
        # https://www.vaultproject.io/docs/auth/approle
        appRole:
          # Path where the App Role authentication backend is mounted
          path: "approle"
          # RoleID configured in the App Role authentication backend
          roleId: "d9eafc08-1dd0-492d-3750-a79b31ae3650"
          # Reference to a key in a K8 Secret that contains the App Role SecretId
          secretRef:
            name: vault-approle-secret
            key: secret-id
            namespace: default
