apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: dev
  namespace: adguard-home
  annotations:
    kargo.akuity.io/color: green
spec:
  requestedFreight:
    - origin:
        kind: Warehouse
        name: adguard-home
      sources:
        direct: true
  promotionTemplate:
    spec:
      steps:
        - task:
            name: promote
          vars:
            - name: chartValuesPath
              value: apps/adguard-home/development
            - name: valuesPath
              value: apps/adguard-home/development
            - name: argocdApp
              value: adguard-home-development
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: pro
  namespace: adguard-home
  annotations:
    kargo.akuity.io/color: red
spec:
  requestedFreight:
    - origin:
        kind: Warehouse
        name: adguard-home
      sources:
        stages:
          - dev
  promotionTemplate:
    spec:
      steps:
        - task:
            name: promote
          vars:
            - name: chartValuesPath
              value: apps/adguard-home/production
            - name: valuesPath
              value: apps/adguard-home/production
            - name: argocdApp
              value: adguard-home-production

