apiVersion: kargo.akuity.io/v1alpha1
kind: Warehouse
metadata:
  name: adguard-home
  namespace: adguard-home
spec:
  subscriptions:
  - image:
      repoURL: docker.io/adguard/adguardhome
      imageSelectionStrategy: SemVer
      strictSemvers: true
      discoveryLimit: 3
      allowTags: '^v\d+\.\d+\.\d+$'
      ignoreTags:
        - '.*-b\.\d+$'

  - chart:
      repoURL: https://squallium.github.io/kubernetes-at-home
      name: adguard-home

