{{- if .Values.externalSecrets.enabled }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ include "servarr.fullname" . }}-config
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: vault-store
    kind: ClusterSecretStore
  target:
    name: {{ include "servarr.fullname" . }}-config
    creationPolicy: Owner
    template:
      type: Opaque
  data:
    {{- with .Values.externalSecrets.data }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
{{- end }}
