fullnameOverride: octoprint

enableServiceLinks: false

image:
  repository: docker.io/octoprint/octoprint

containerPort: 80

volumeMounts:
  - name: octoprint
    mountPath: /octoprint


volumes:
  - name: octoprint
    hostPath:
      path: /mnt/services/octoprint
      type: DirectoryOrCreate

serviceAccount:
  create: false

ingress:
  enabled: true

resources:
  requests:
    cpu: "50m"
    memory: "64Mi"
  limits:
    cpu: "1000m"
    memory: "1Gi"

readinessProbe:
  httpGet:
    path: /
    port: http
  initialDelaySeconds: 30
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 6

livenessProbe:
  httpGet:
    path: /
    port: http
  initialDelaySeconds: 60
  periodSeconds: 20
  timeoutSeconds: 5
  failureThreshold: 3