fullnameOverride: octoprint

enableServiceLinks: false

image:
  repository: docker.io/octoprint/octoprint

containerPort: 80

volumeMounts:
  - name: octoprint
    mountPath: /octoprint


volumes:
  - name: octoprint
    hostPath:
      path: /mnt/services/octoprint
      type: DirectoryOrCreate

serviceAccount:
  create: false

ingress:
  enabled: true

resources:
  requests:
    cpu: "50m"
    memory: "64Mi"
  limits:
    cpu: "1000m"
    memory: "1Gi"