apiVersion: apps/v1
kind: Deployment
metadata:
  name: paperless-redis
spec:
  selector:
    matchLabels:
      app: paperless-redis
  template:
    metadata:
      labels:
        app: paperless-redis
    spec:
      containers:
        - name: redis
          image: {{ .Values.redis.image }}
          ports:
            - containerPort: 6379
          volumeMounts:
            - name: redisdata
              mountPath: /data
      volumes:
        - name: redisdata
          hostPath:
            path: {{ .Values.redis.storagePath }}
            type: Directory
---
apiVersion: v1
kind: Service
metadata:
  name: paperless-redis
spec:
  selector:
    app: paperless-redis
  ports:
    - protocol: TCP
      port: 6379
