applicationsets:
  {%- for addon in cookiecutter.addons.list %}
  {{ addon.name }}:
    namespace: argocd
    additionalLabels: {}
    additionalAnnotations: {}
    finalizers:
      - resources-finalizer.argocd.argoproj.io
    # See PR #10026 (ArgoCD v2.5 or later)
    # goTemplate: false
    generators:
      - matrix:
          generators:
            - clusters: {}
            - git:
                repoURL: https://github.com/Squallium/kubernetes-at-home.git
                revision: main
                files:
                  - path: 'addons/{{ addon.name }}/{{'{{'}}metadata.labels.environment}}/values.yaml'
    # Ref https://argo-cd.readthedocs.io/en/stable/operator-manual/applicationset/Controlling-Resource-Modification/#allow-temporarily-toggling-auto-sync
    ignoreApplicationDifferences:
      - jsonPointers:
          - /spec/syncPolicy
    # Progressive Syncs is an experimental feature and it must be explicitly enabled
    # Ref: https://argo-cd.readthedocs.io/en/stable/operator-manual/applicationset/Progressive-Syncs/#enabling-progressive-syncs
    #      strategy:
    #        type: RollingSync
    #        rollingSync:
    #          steps:
    #          - matchExpressions:
    #            - key: project
    #              operator: In
    #              values:
    #              - guestbook
    #          - matchExpressions:
    #            - key: project
    #              operator: In
    #              values:
    #              - kustomize-foo
    #              - kustomize-bar
    template:
      metadata:
        name: '{{ addon.name }}-{{'{{'}}metadata.labels.environment}}'
        labels:
          type: 'addon'
        annotations: {}
      spec:
        project: default
        sources:
          - repoURL: https://github.com/Squallium/kubernetes-at-home.git
            targetRevision: main
            ref: values
          {%- if addon.chart_name | default(cookiecutter.default_chart_name) %}
          - repoURL: {{ addon.chart_repo | default(cookiecutter.default_chart_repo) }}
            chart: {{ addon.chart_name  }}
          {%- else %}
          - repoURL: {{ addon.chart_repo_url | default(cookiecutter.default_chart_repo_url) }}
            path: charts/{{ addon.name }}
          {%- endif %}
            targetRevision: {{ addon.chart_target_revision | default(cookiecutter.default_chart_target_revision) }}
            helm:
              valueFiles:
                - $values/addons/{{ addon.name }}/values.yaml
                - $values/addons/{{ addon.name }}/{{'{{'}}metadata.labels.environment}}/values.yaml
                {%- if addon.get("enable_ssl", False) %}
                - $values/addons/{{ addon.name }}/{{'{{'}}metadata.labels.environment}}/values-ssl.yaml
                {%- endif %}
        destination:
          server: '{{'{{'}}server}}'
          namespace: {{ addon.name }}
        syncPolicy:
#            automated:
#              prune: false
#              selfHeal: false
          syncOptions:
            - CreateNamespace=true
        ignoreDifferences:
          - group: apps
            kind: Deployment
            jsonPointers:
              - /spec/replicas
        info:
          - name: url
            value: https://argoproj.github.io/
    syncPolicy:
      # Set Application finalizer
      preserveResourcesOnDeletion: true
    # Templating is only available on string type
  #      templatePatch: |
  #        spec:
  #          source:
  #            helm:
  #              valueFiles:
  #              {{'{{'}}- range $valueFile := .valueFiles }}
  #                - {{'{{'}} $valueFile }}
  #              {{'{{'}}- end }}
  #        {{'{{'}}- if .autoSync }}
  #          syncPolicy:
  #            automated:
  #              prune: {{'{{'}} .prune }}
  #        {{'{{'}}- end }}
  {%- endfor %}
  {%- for addon_config in cookiecutter.addons_config.list %}
  {{ addon_config.name }}-config:
    namespace: argocd
    additionalLabels: {}
    additionalAnnotations: {}
    finalizers:
      - resources-finalizer.argocd.argoproj.io
    # See PR #10026 (ArgoCD v2.5 or later)
    # goTemplate: false
    generators:
      - matrix:
          generators:
            - clusters: {}
            - git:
                repoURL: https://github.com/Squallium/kubernetes-at-home.git
                revision: main
                files:
                  - path: 'addons/{{ addon_config.name }}/config/{{'{{'}}metadata.labels.environment}}/values.yaml'
    # Ref https://argo-cd.readthedocs.io/en/stable/operator-manual/applicationset/Controlling-Resource-Modification/#allow-temporarily-toggling-auto-sync
    ignoreApplicationDifferences:
      - jsonPointers:
          - /spec/syncPolicy
    # Progressive Syncs is an experimental feature and it must be explicitly enabled
    # Ref: https://argo-cd.readthedocs.io/en/stable/operator-manual/applicationset/Progressive-Syncs/#enabling-progressive-syncs
    #      strategy:
    #        type: RollingSync
    #        rollingSync:
    #          steps:
    #          - matchExpressions:
    #            - key: project
    #              operator: In
    #              values:
    #              - guestbook
    #          - matchExpressions:
    #            - key: project
    #              operator: In
    #              values:
    #              - kustomize-foo
    #              - kustomize-bar
    template:
      metadata:
        name: '{{ addon_config.name }}-config-{{'{{'}}metadata.labels.environment}}'
        labels:
          type: 'addon-config'
        annotations: {}
      spec:
        project: default
        sources:
          - repoURL: https://github.com/Squallium/kubernetes-at-home.git
            targetRevision: main
            ref: values
          {%- if addon_config.chart_name | default(cookiecutter.default_chart_name) %}
          - repoURL: {{ addon_config.chart_repo | default(cookiecutter.default_chart_repo) }}
            chart: {{ addon_config.chart_name  }}
          {%- else %}
          - repoURL: {{ addon_config.chart_repo_url | default(cookiecutter.default_chart_repo_url) }}
            path: charts/{{ addon_config.name }}
          {%- endif %}
            targetRevision: {{ addon_config.chart_target_revision | default(cookiecutter.default_chart_target_revision) }}
            helm:
              valueFiles:
                - $values/addons/{{ addon_config.name }}/config/values.yaml
                - $values/addons/{{ addon_config.name }}/config/{{'{{'}}metadata.labels.environment}}/values.yaml
        destination:
          server: '{{'{{'}}server}}'
          namespace: {{ addon_config.namespace | default(addon_config.name) }}
        syncPolicy:
#            automated:
#              prune: false
#              selfHeal: false
          syncOptions:
            - CreateNamespace=true
        ignoreDifferences:
          - group: apps
            kind: Deployment
            jsonPointers:
              - /spec/replicas
        info:
          - name: url
            value: https://argoproj.github.io/
    syncPolicy:
      # Set Application finalizer
      preserveResourcesOnDeletion: true
    # Templating is only available on string type
  #      templatePatch: |
  #        spec:
  #          source:
  #            helm:
  #              valueFiles:
  #              {{'{{'}}- range $valueFile := .valueFiles }}
  #                - {{'{{'}} $valueFile }}
  #              {{'{{'}}- end }}
  #        {{'{{'}}- if .autoSync }}
  #          syncPolicy:
  #            automated:
  #              prune: {{'{{'}} .prune }}
  #        {{'{{'}}- end }}
  {%- endfor %}