apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mycluster-ca
  namespace: cert-manager
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-store
    kind: ClusterSecretStore
  target:
    name: mycluster-ca
    template:
      type: kubernetes.io/tls
    creationPolicy: Owner
  data:
    - secretKey: tls.crt
      remoteRef:
        key: secret/cert-manager/root-ca
        property: tls.crt
    - secretKey: tls.key
      remoteRef:
        key: secret/cert-manager/root-ca
        property: tls.key
