replicaCount: 1

image:
  repository: ghcr.io/sysadminsmedia/homebox
  tag: latest
  pullPolicy: IfNotPresent

persistence:
  enabled: true
  storageClass: hostpath-storage
  size: 1Gi

ingress:
  enabled: true
  className: public
  host: homebox.local.lan

resources: {}
