replicaCount: 1

image:
  repository: ghcr.io/sysadminsmedia/homebox
  tag: v0.19.0
  pullPolicy: IfNotPresent

persistence:
  enabled: true
  storageClass: microk8s-hostpath
  size: 1Gi

ingress:
  enabled: true
  className: public
  host: homebox.local.lan

resources: {}
