chart:
  targetRevision: 0.0.7
extSecrets:
  - name: api
    secrets:
      - secretKey: ADMIN_ACCOUNT_PASSWORD_HASH
        remoteRef:
          key: secret/kargo/api
      - secretKey: ADMIN_ACCOUNT_TOKEN_SIGNING_KEY
        remoteRef:
          key: secret/kargo/api
argocd-apps:
  applicationsets:
    {%- set addon_names = (cookiecutter.addons.list | default([]) | map(attribute='name') | list) %}
    {%- set merged_addons = (cookiecutter.addons.list | default([])) + (cookiecutter.addons_config.list | default([]) | rejectattr('name', 'in', addon_names) | list ) %}
    {%- set groups = [
      ("kargo-core-projects", "service", "apps", "", "-core", cookiecutter.core_services.list | default([])),
      ("kargo-projects", "service", "apps", "", "", cookiecutter.services.list | default([])),
      ("kargo-projects-addons", "addon", "addons", "addon-", "", merged_addons | default([])),
    ] %}
    {%- for group_name, type, folder, prefix, suffix, services_list in groups
     if services_list | length > 0 %}
    {{ group_name }}:
      namespace: argocd
      additionalLabels: {}
      additionalAnnotations: {}
      finalizers:
        - resources-finalizer.argocd.argoproj.io
      # See PR #10026 (ArgoCD v2.5 or later)
      # goTemplate: false
      generators:
        - matrix:
            generators:
              - list:
                  elements:
                    {%- for service in (services_list  | default([]) | selectattr('enable_kargo', 'defined') | selectattr('enable_kargo') ) %}
                    - {{ type }}: {{ service.name }}
                      location: {{ service.name }}
                    {%- for addon in (service.addons | default({})).list | default([]) %}
                    - {{ type }}: {{ addon.name }}
                      location: {{ addon.location }}
                    {%- endfor %}
                    {%- endfor %}
              - git:
                  repoURL: https://github.com/Squallium/kubernetes-at-home.git
                  revision: main
                  files:
                    - path: '{{folder}}/{{'{{'}}location}}/kargo.yaml'
      # Ref https://argo-cd.readthedocs.io/en/stable/operator-manual/applicationset/Controlling-Resource-Modification/#allow-temporarily-toggling-auto-sync
      ignoreApplicationDifferences:
        - jsonPointers:
            - /spec/syncPolicy
      # Progressive Syncs is an experimental feature and it must be explicitly enabled
      # Ref: https://argo-cd.readthedocs.io/en/stable/operator-manual/applicationset/Progressive-Syncs/#enabling-progressive-syncs
      #      strategy:
      #        type: RollingSync
      #        rollingSync:
      #          steps:
      #          - matchExpressions:
      #            - key: project
      #              operator: In
      #              values:
      #              - guestbook
      #          - matchExpressions:
      #            - key: project
      #              operator: In
      #              values:
      #              - kustomize-foo
      #              - kustomize-bar
      template:
        metadata:
          name: 'kargo-{{ prefix }}{{'{{'}}{{ type }}}}{{ suffix }}'
          labels:
            type: 'kargo-project'
          annotations: {}
        spec:
          project: default
          sources:
            - repoURL: https://github.com/Squallium/kubernetes-at-home.git
              targetRevision: main
              ref: values
            - repoURL: https://squallium.github.io/kubernetes-at-home
              chart: kargo-project
              targetRevision: '{{'{{'}}chart.targetRevision}}'
              helm:
                valueFiles:
                  - $values/{{folder}}/{{'{{'}}location}}/kargo.yaml
                values: |
                  kargo:
                    name: '{{'{{'}}{{ type }}}}'
                    type: {{ folder }}
                    location: '{{'{{'}}location}}'
                    project:
                      name: '{{ prefix }}{{'{{'}}{{ type }}}}{{ suffix }}'
          destination:
            server: https://kubernetes.default.svc
            namespace: '{{ prefix }}{{'{{'}}{{ type }}}}'
          syncPolicy:
            #            automated:
            #              prune: false
            #              selfHeal: false
            syncOptions:
              - CreateNamespace=false
          ignoreDifferences:
            - group: apps
              kind: Deployment
              jsonPointers:
                - /spec/replicas
          info:
            - name: url
              value: https://argoproj.github.io/
      syncPolicy:
        # Set Application finalizer
        preserveResourcesOnDeletion: true
      # Templating is only available on string type
    #      templatePatch: |
    #        spec:
    #          source:
    #            helm:
    #              valueFiles:
    #              {{'{{'}}- range $valueFile := .valueFiles }}
    #                - {{'{{'}} $valueFile }}
    #              {{'{{'}}- end }}
    #        {{'{{'}}- if .autoSync }}
    #          syncPolicy:
    #            automated:
    #              prune: {{'{{'}} .prune }}
    #        {{'{{'}}- end }}
    {%- endfor %}