extSecrets:
  - name: api
    secrets:
      - secretKey: ADMIN_ACCOUNT_PASSWORD_HASH
        remoteRef:
          key: secret/kargo/api
      - secretKey: ADMIN_ACCOUNT_TOKEN_SIGNING_KEY
        remoteRef:
          key: secret/kargo/api
  - name: home-assistant-github-ssh
    namespace: home-assistant
    labels:
      kargo.akuity.io/cred-type: git
    secrets:
      - secretKey: repoURL
        remoteRef:
          key: secret/kargo/github
          property: repo_url
      - secretKey: sshPrivateKey
        remoteRef:
          key: secret/kargo/github
          property: ssh_private_key
  - name: calibre-web-github-ssh
    namespace: calibre-web
    labels:
      kargo.akuity.io/cred-type: git
    secrets:
      - secretKey: repoURL
        remoteRef:
          key: secret/kargo/github
          property: repo_url
      - secretKey: sshPrivateKey
        remoteRef:
          key: secret/kargo/github
          property: ssh_private_key
  - name: docker
    namespace: adguard-home
    labels:
      kargo.akuity.io/cred-type: image
    secrets:
      - secretKey: repoURL
        remoteRef:
          key: secret/kargo/docker
          property: repo_url
      - secretKey: username
        remoteRef:
          key: secret/kargo/docker
          property: username
      - secretKey: password
        remoteRef:
          key: secret/kargo/docker
          property: password
argocd-apps:
  applicationsets:
    kargo-projects:
      namespace: argocd
      additionalLabels: {}
      additionalAnnotations: {}
      finalizers:
        - resources-finalizer.argocd.argoproj.io
      # See PR #10026 (ArgoCD v2.5 or later)
      # goTemplate: false
      generators:
        - matrix:
            generators:
              - list:
                  elements:
                    - service: calibre-web
              - git:
                  repoURL: https://github.com/Squallium/kubernetes-at-home.git
                  revision: main
                  files:
                    - path: 'apps/{{service}}/kargo.yaml'
      # Ref https://argo-cd.readthedocs.io/en/stable/operator-manual/applicationset/Controlling-Resource-Modification/#allow-temporarily-toggling-auto-sync
      ignoreApplicationDifferences:
        - jsonPointers:
            - /spec/syncPolicy
      # Progressive Syncs is an experimental feature and it must be explicitly enabled
      # Ref: https://argo-cd.readthedocs.io/en/stable/operator-manual/applicationset/Progressive-Syncs/#enabling-progressive-syncs
      #      strategy:
      #        type: RollingSync
      #        rollingSync:
      #          steps:
      #          - matchExpressions:
      #            - key: project
      #              operator: In
      #              values:
      #              - guestbook
      #          - matchExpressions:
      #            - key: project
      #              operator: In
      #              values:
      #              - kustomize-foo
      #              - kustomize-bar
      template:
        metadata:
          name: 'kargo-{{service}}'
          labels:
            type: 'kargo-project'
          annotations: {}
        spec:
          project: default
          sources:
            - repoURL: https://github.com/Squallium/kubernetes-at-home.git
              targetRevision: main
              ref: values
            - repoURL: https://squallium.github.io/kubernetes-at-home
              chart: kargo-project
              targetRevision: '{{chart.targetRevision}}'
              helm:
                valueFiles:
                  - $values/apps/{{service}}/kargo.yaml
          destination:
            server: https://kubernetes.default.svc
            namespace: '{{service}}'
          syncPolicy:
            #            automated:
            #              prune: false
            #              selfHeal: false
            syncOptions:
              - CreateNamespace=true
          ignoreDifferences:
            - group: apps
              kind: Deployment
              jsonPointers:
                - /spec/replicas
          info:
            - name: url
              value: https://argoproj.github.io/
      syncPolicy:
        # Set Application finalizer
        preserveResourcesOnDeletion: true
      # Templating is only available on string type
    #      templatePatch: |
    #        spec:
    #          source:
    #            helm:
    #              valueFiles:
    #              {{- range $valueFile := .valueFiles }}
    #                - {{ $valueFile }}
    #              {{- end }}
    #        {{- if .autoSync }}
    #          syncPolicy:
    #            automated:
    #              prune: {{ .prune }}
    #        {{- end }}