extSecrets:
  - name: api
    secrets:
      - secretKey: ADMIN_ACCOUNT_PASSWORD_HASH
        remoteRef:
          key: secret/kargo/api
      - secretKey: ADMIN_ACCOUNT_TOKEN_SIGNING_KEY
        remoteRef:
          key: secret/kargo/api
  - name: home-assistant-github-ssh
    namespace: home-assistant
    labels:
      kargo.akuity.io/cred-type: git
    secrets:
      - secretKey: repoURL
        remoteRef:
          key: secret/kargo/github
          property: repo_url
      - secretKey: sshPrivateKey
        remoteRef:
          key: secret/kargo/github
          property: ssh_private_key
  - name: calibre-web-github-ssh
    namespace: calibre-web
    labels:
      kargo.akuity.io/cred-type: git
    secrets:
      - secretKey: repoURL
        remoteRef:
          key: secret/kargo/github
          property: repo_url
      - secretKey: sshPrivateKey
        remoteRef:
          key: secret/kargo/github
          property: ssh_private_key
  - name: docker
    namespace: adguard-home
    labels:
      kargo.akuity.io/cred-type: image
    secrets:
      - secretKey: repoURL
        remoteRef:
          key: secret/kargo/docker
          property: repo_url
      - secretKey: username
        remoteRef:
          key: secret/kargo/docker
          property: username
      - secretKey: password
        remoteRef:
          key: secret/kargo/docker
          property: password