apiVersion: kargo.akuity.io/v1alpha1
kind: PromotionTask
metadata:
  name: promote
  namespace: home-assistant
spec:
  vars:
  - name: chart
    value: https://pajikos.github.io/home-assistant-helm-chart
  - name: image
    value: ghcr.io/home-assistant/home-assistant
  - name: repoURL
    value: git@github.com:Squallium/kubernetes-at-home.git
  - name: branch
    value: main
  - name: chartValuesPath
  - name: valuesPath
  - name: argocdApp

  steps:
  - uses: git-clone
    config:
      repoURL: ${{ vars.repoURL }}
      checkout:
      - branch: ${{ vars.branch }}
        path: ./out
  # update the chart version
  - uses: yaml-update
    as: update-chart
    config:
      path: ./out/${{ vars.chartValuesPath }}/config.yaml
      updates:
        - key: chart.targetRevision
          value: ${{ chartFrom( vars.chart, "home-assistant", warehouse("home-assistant") ).Version }}
  - uses: git-commit
    as: commit-chart
    config:
      path: ./out
      message: ${{ task.outputs['update-chart'].commitMessage }}
  # update the image version
  - uses: yaml-update
    as: update-image
    config:
      path: ./out/${{ vars.valuesPath }}/values.yaml
      updates:
      - key: image.tag
        value: ${{ imageFrom( vars.image, warehouse("home-assistant") ).Tag }}
  - uses: git-commit
    as: commit-image
    config:
      path: ./out
      message: ${{ task.outputs['update-image'].commitMessage }}
  - uses: git-push
    config:
      path: ./out
  - uses: argocd-update
    config:
      apps:
      - name: ${{ vars.argocdApp }}

