apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: dev
  namespace: home-assistant
  annotations:
    kargo.akuity.io/color: green
spec:
  requestedFreight:
    - origin:
        kind: Warehouse
        name: home-assistant
      sources:
        direct: true
  promotionTemplate:
    spec:
      steps:
        - task:
            name: promote
          vars:
            - name: chartValuesPath
              value: apps/home-assistant/development
            - name: valuesPath
              value: apps/home-assistant/development
            - name: argocdApp
              value: home-assistant-development
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: pro
  namespace: home-assistant
  annotations:
    kargo.akuity.io/color: red
spec:
  requestedFreight:
    - origin:
        kind: Warehouse
        name: home-assistant
      sources:
        stages:
          - dev
  promotionTemplate:
    spec:
      steps:
        - task:
            name: promote
          vars:
            - name: chartValuesPath
              value: apps/home-assistant/production
            - name: valuesPath
              value: apps/home-assistant/production
            - name: argocdApp
              value: home-assistant-production

