apiVersion: kargo.akuity.io/v1alpha1
kind: Warehouse
metadata:
  name: home-assistant
  namespace: home-assistant
spec:
  subscriptions:
  - image:
      repoURL: ghcr.io/home-assistant/home-assistant
      imageSelectionStrategy: SemVer
  - chart:
      repoURL: https://pajikos.github.io/home-assistant-helm-chart
      name: home-assistant

