ingress:
  enabled: true
  className: public
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"

securityContext:
  privileged: true

persistence:
  enabled: true
  existingVolume: home-assistant-config
  storageClass: microk8s-hostpath

configuration:
  enabled: true
  forceInit: true
  trusted_proxies:
    - 10.0.0.0/8
    - 127.0.0.1
    - ::1
