ingress:
  enabled: true
  className: public
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"

securityContext:
  privileged: true

persistence:
  enabled: true
  existingVolume: home-assistant-config
  storageClass: microk8s-hostpath

configuration:
  enabled: true
  forceInit: true
  trusted_proxies:
    - 10.0.0.0/8
    - 127.0.0.1
    - ::1
  templateConfig: |-
    # Loads default set of integrations. Do not remove.
    default_config:
    
    {{- if or .Values.ingress.enabled .Values.ingress.external }}
    http:
      use_x_forwarded_for: true
      trusted_proxies:
        {{- range .Values.configuration.trusted_proxies }}
        - {{ . }}
        {{- end }}
    {{- end}}
    # Load frontend themes from the themes folder
    frontend:
      themes: !include_dir_merge_named themes
    
    automation: !include automations.yaml
    script: !include scripts.yaml
    scene: !include scenes.yaml