apiVersion: batch/v1
kind: CronJob
metadata:
  name: install-hacs
  namespace: home-assistant
spec:
  schedule: "@daily"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: install-hacs
              image: alpine:3.20
              command:
                - sh
                - -c
                - |
                  echo "[HACS CronJob] Instalando HACS si no existe..."
                  apk add --no-cache curl unzip
                  if [ ! -d /config/custom_components/hacs ]; then
                    echo "Descargando HACS..."
                    curl -sfSL https://github.com/hacs/integration/releases/latest/download/hacs.zip -o /tmp/hacs.zip
                    unzip -q /tmp/hacs.zip -d /config/custom_components/hacs
                    echo "HACS instalado."
                  else
                    echo "HACS ya está instalado. Nada que hacer."
                  fi
              volumeMounts:
                - name: config
                  mountPath: /config
          restartPolicy: OnFailure
          volumes:
            - name: config
              persistentVolumeClaim:
                claimName: home-assistant-config
