apiVersion: apps/v1
kind: Deployment
metadata:
  name: zigbee2mqtt
  labels:
    app: zigbee2mqtt
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zigbee2mqtt
  template:
    metadata:
      labels:
        app: zigbee2mqtt
    spec:
      hostPID: false
      containers:
        - name: zigbee2mqtt
          image: koenkk/zigbee2mqtt:1.38.0
          securityContext:
            privileged: true
          env:
            - name: TZ
              value: Europe/Madrid
          volumeMounts:
            - name: config
              mountPath: /app/data
            - name: usb
              mountPath: /dev/ttyUSB0
              readOnly: true
      volumes:
        - name: config
          hostPath:
            path: /mnt/home-assistant/zigbee2mqtt/config
            type: Directory
        - name: usb
          hostPath:
            path: /dev/ttyUSB0
            type: CharDevice
---
apiVersion: v1
kind: Service
metadata:
  name: zigbee2mqtt
  labels:
    app: zigbee2mqtt
spec:
  selector:
    app: zigbee2mqtt
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
