apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: authentik-env
  namespace: authentik
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-store
    kind: ClusterSecretStore
  target:
    name: authentik-env
    creationPolicy: Owner
  data:
    - secretKey: AUTHENTIK_SECRET_KEY
      remoteRef:
        key: {{ .Values.vault.envSecretPath }}
        property: AUTHENTIK_SECRET_KEY
