apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: authentik-db
  namespace: authentik
spec:
  instances: 1
  imageName: ghcr.io/cloudnative-pg/postgresql:16

  storage:
    storageClass: microk8s-hostpath
    size: 2Gi

  bootstrap:
    initdb:
      database: authentik
      owner: authentik
      secret:
        name: authentik-postgres

  superuserSecret:
    name: authentik-postgres

  monitoring:
    enablePodMonitor: false
