applications:
  cert-manager:
    namespace: argocd
    additionalLabels: {}
    additionalAnnotations: {}
    finalizers:
    - resources-finalizer.argocd.argoproj.io
    project: default
    sources:
    - repoURL: https://github.com/Squallium/kubernetes-at-home.git
      targetRevision: main
      ref: values
    - repoURL: https://charts.jetstack.io
      chart: cert-manager
      targetRevision: 1.18.2
      helm:
        valueFiles:
          - $values/apps/cert-manager/values.yaml
    destination:
      server: https://kubernetes.default.svc
      namespace: cert-manager
    syncPolicy:
#      automated:
#        prune: false
#        selfHeal: false
      syncOptions:
      - CreateNamespace=true
    revisionHistoryLimit: null
    ignoreDifferences:
    - group: apps
      kind: Deployment
      jsonPointers:
      - /spec/replicas
    info:
    - name: url
      value: https://argoproj.github.io/