#TODO set in a kubernetes secret
rootUser: miUsuario
rootPassword: miPasswordSegura

mode: standalone

persistence:
  enabled: true
  existingClaim: minio

resources:
  requests:
    memory: 512Mi
    cpu: 250m

ingress:
  enabled: true
  ingressClassName: public
  hosts:
    - minio.internal

consoleIngress:
  enabled: true
  ingressClassName: public
  hosts:
    - minio-ui.internal