#TODO set in a kubernetes secret
rootUser: miUsuario
rootPassword: miPasswordSegura

mode: standalone

persistence:
  enabled: true
  existingClaim: ""
  storageClass: microk8s-hostpath
  accessMode: ReadWriteOnce
  size: 10Gi
  mountPath: /export
  type: hostPath
  hostPath: /mnt/minio/export

resources:
  requests:
    memory: 512Mi
    cpu: 250m

ingress:
  enabled: true
  ingressClassName: public
  hosts:
    - minio.internal

consoleIngress:
  enabled: true
  ingressClassName: public
  hosts:
    - minio-ui.internal