mode: standalone

environment:
  MINIO_SERVER_URL: http://minio.internal
  MINIO_BROWSER_REDIRECT_URL: http://minio-ui.internal

persistence:
  enabled: true
  existingClaim: ""
  storageClass: "microk8s-hostpath"
  accessMode: ReadWriteOnce
  size: 10Gi
  mountPath: /data
  type: hostPath
  hostPath: /mnt/minio/data

resources:
  requests:
    memory: 512Mi
    cpu: 250m

ingress:
  enabled: true
  ingressClassName: public
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
  hosts:
    - minio.internal

consoleIngress:
  enabled: true
  ingressClassName: public
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
  hosts:
    - minio-ui.internal