#argocd-apps:
#  applications:
#    zigbee2mqtt:
#      namespace: argocd
#      additionalLabels: {}
#      additionalAnnotations: {}
#      finalizers:
#      - resources-finalizer.argocd.argoproj.io
#      project: default
#      sources:
#      - repoURL: https://github.com/Squallium/kubernetes-at-home.git
#        targetRevision: main
#        ref: values
#      - repoURL: https://koenkk.github.io/zigbee2mqtt-chart
#        chart: zigbee2mqtt
#        targetRevision: 2.4.0
#        helm:
#          valueFiles:
#            - $values/apps/home-assistant/config/zigbee2mqtt/development/values.yaml
#      destination:
#        server: https://kubernetes.default.svc
#        namespace: home-assistant
#      syncPolicy:
#  #      automated:
#  #        prune: false
#  #        selfHeal: false
#        syncOptions:
#        - CreateNamespace=true
#      revisionHistoryLimit: null
#      ignoreDifferences:
#      - group: apps
#        kind: Deployment
#        jsonPointers:
#        - /spec/replicas
#      info:
#      - name: url
#        value: https://argoproj.github.io/