argocd-apps:
  applicationsets:
    hacs:
      namespace: argocd
      additionalLabels: {}
      additionalAnnotations: {}
      finalizers:
        - resources-finalizer.argocd.argoproj.io
      # See PR #10026 (ArgoCD v2.5 or later)
      # goTemplate: false
      generators:
        - matrix:
            generators:
              - clusters: {}
              - git:
                  repoURL: https://github.com/Squallium/kubernetes-at-home.git
                  revision: main
                  files:
                    - path: 'apps/home-assistant-addons/hacs/{{metadata.labels.environment}}/values.yaml'
      # Ref https://argo-cd.readthedocs.io/en/stable/operator-manual/applicationset/Controlling-Resource-Modification/#allow-temporarily-toggling-auto-sync
      ignoreApplicationDifferences:
        - jsonPointers:
            - /spec/syncPolicy
      # Progressive Syncs is an experimental feature and it must be explicitly enabled
      # Ref: https://argo-cd.readthedocs.io/en/stable/operator-manual/applicationset/Progressive-Syncs/#enabling-progressive-syncs
      #      strategy:
      #        type: RollingSync
      #        rollingSync:
      #          steps:
      #          - matchExpressions:
      #            - key: project
      #              operator: In
      #              values:
      #              - guestbook
      #          - matchExpressions:
      #            - key: project
      #              operator: In
      #              values:
      #              - kustomize-foo
      #              - kustomize-bar
      template:
        metadata:
          name: 'hacs-{{metadata.labels.environment}}'
          labels:
            type: 'service'
          annotations: {}
        spec:
          project: default
          sources:
            - repoURL: https://github.com/Squallium/kubernetes-at-home.git
              targetRevision: main
              ref: values
            - repoURL: https://squallium.github.io/kubernetes-at-home
              chart: hacs
              targetRevision: 0.0.3
              helm:
                valueFiles:
                  - $values/apps/home-assistant-addons/hacs/values.yaml
                  - $values/apps/home-assistant-addons/hacs/{{metadata.labels.environment}}/values.yaml
          destination:
            server: '{{server}}'
            namespace: home-assistant
          syncPolicy:
            #            automated:
            #              prune: false
            #              selfHeal: false
            syncOptions:
              - CreateNamespace=true
          ignoreDifferences:
            - group: apps
              kind: Deployment
              jsonPointers:
                - /spec/replicas
          info:
            - name: url
              value: https://argoproj.github.io/
      syncPolicy:
        # Set Application finalizer
        preserveResourcesOnDeletion: false
      # Templating is only available on string type
      #      templatePatch: |
      #        spec:
      #          source:
      #            helm:
      #              valueFiles:
      #              {{- range $valueFile := .valueFiles }}
      #                - {{ $valueFile }}
      #              {{- end }}
      #        {{- if .autoSync }}
      #          syncPolicy:
      #            automated:
      #              prune: {{ .prune }}
      #        {{- end }}
    zigbee2mqtt:
      namespace: argocd
      additionalLabels: {}
      additionalAnnotations: {}
      finalizers:
        - resources-finalizer.argocd.argoproj.io
      # See PR #10026 (ArgoCD v2.5 or later)
      # goTemplate: false
      generators:
        - matrix:
            generators:
              - clusters: {}
              - git:
                  repoURL: https://github.com/Squallium/kubernetes-at-home.git
                  revision: main
                  files:
                    - path: 'apps/home-assistant-addons/zigbee2mqtt/{{metadata.labels.environment}}/values.yaml'
      # Ref https://argo-cd.readthedocs.io/en/stable/operator-manual/applicationset/Controlling-Resource-Modification/#allow-temporarily-toggling-auto-sync
      ignoreApplicationDifferences:
        - jsonPointers:
            - /spec/syncPolicy
      # Progressive Syncs is an experimental feature and it must be explicitly enabled
      # Ref: https://argo-cd.readthedocs.io/en/stable/operator-manual/applicationset/Progressive-Syncs/#enabling-progressive-syncs
      #      strategy:
      #        type: RollingSync
      #        rollingSync:
      #          steps:
      #          - matchExpressions:
      #            - key: project
      #              operator: In
      #              values:
      #              - guestbook
      #          - matchExpressions:
      #            - key: project
      #              operator: In
      #              values:
      #              - kustomize-foo
      #              - kustomize-bar
      template:
        metadata:
          name: 'zigbee2mqtt-{{metadata.labels.environment}}'
          labels:
            type: 'service'
          annotations: {}
        spec:
          project: default
          sources:
            - repoURL: https://github.com/Squallium/kubernetes-at-home.git
              targetRevision: main
              ref: values
            - repoURL: https://koenkk.github.io/zigbee2mqtt-chart
              chart: zigbee2mqtt
              targetRevision: 2.4.0
              helm:
                valueFiles:
                  - $values/apps/home-assistant-addons/zigbee2mqtt/values.yaml
                  - $values/apps/home-assistant-addons/zigbee2mqtt/{{metadata.labels.environment}}/values.yaml
          destination:
            server: '{{server}}'
            namespace: home-assistant
          syncPolicy:
#            automated:
#              prune: false
#              selfHeal: false
            syncOptions:
              - CreateNamespace=true
          ignoreDifferences:
            - group: apps
              kind: Deployment
              jsonPointers:
                - /spec/replicas
          info:
            - name: url
              value: https://argoproj.github.io/
      syncPolicy:
        # Set Application finalizer
        preserveResourcesOnDeletion: false
      # Templating is only available on string type
    #      templatePatch: |
    #        spec:
    #          source:
    #            helm:
    #              valueFiles:
    #              {{- range $valueFile := .valueFiles }}
    #                - {{ $valueFile }}
    #              {{- end }}
    #        {{- if .autoSync }}
    #          syncPolicy:
    #            automated:
    #              prune: {{ .prune }}
    #        {{- end }}