extSecrets:
  - name: env
    secrets:
      - secretKey: AUTHENTIK_SECRET_KEY
        remoteRef:
          key: secret/authentik/development/env
  - name: postgres
    templateType: kubernetes.io/basic-auth
    secrets:
      - secretKey: username
        remoteRef:
          key: secret/authentik/development/postgres
          property: username
      - secretKey: password
        remoteRef:
          key: secret/authentik/development/postgres
          property: password