image:
  tag: 4.7.0

ingress:
  enabled: true
  hosts:
    - host: romm.internal
      paths:
        - path: /
          pathType: ImplementationSpecific

envSecretKeys:
  mariadb: secret/romm/production/mariadb
  config: secret/romm/production/config