ingress:
  annotations:
    cert-manager.io/cluster-issuer: home-internal-ca-issuer
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
  tls:
    - hosts:
        - paperless-dev.internal
      secretName: paperless-dev-internal-tls