global:
  tlsDisable: false

server:
  ingress:
    annotations:
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
    tls:
      - secretName: vault-internal-tls
        hosts:
          - vault.internal