global:
  tlsDisable: true

ui:
  enabled: true
  serviceType: LoadBalancer

server:
  enabled: true
  ha:
    enabled: false
  standalone:
    enabled: true

  dataStorage:
    enabled: false
    
  volumes:
    - name: vault-data
      persistentVolumeClaim:
        claimName: vault-pvc

  volumeMounts:
    - name: vault-data
      mountPath: /vault/data

  ingress:
    enabled: true
    annotations:
      nginx.ingress.kubernetes.io/ssl-redirect: "false"
    hosts:
      - host: vault.internal
        paths:
          - /
