global:
  tlsDisable: false

ui:
  enabled: true
  serviceType: LoadBalancer

server:
  enabled: true
  ha:
    enabled: false
  dataStorage:
    enabled: true
    size: 2Gi
    storageClass: microk8s-hostpath
  standalone:
    enabled: true
  ingress:
    enabled: true
    annotations:
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
    hosts:
      - host: vault.internal
        paths:
          - /
    tls:
      - secretName: vault-internal-tls
        hosts:
          - vault.internal
