apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudflared-config
data:
  config.yml: |
    tunnel: home-assistant
    ingress:
      - hostname: ha.thejedisway.com
        service: http://home-assistant-production.home-assistant.svc.cluster.local:8080
      - service: http_status:404
