image:
  tag: 0.6.27
deployment:
  additionalVolumeMounts:
    - name: books
      mountPath: /books
  additionalVolumes:
    - name: books
      hostPathPath: /mnt/services/calibre-web/calibre-library
ingress:
  hostname: calibre-web.thejedisway.com
