server:
  ingress:
    enabled: true
    ingressClassName: public
    hostname: argocd.internal

  service:
    type: ClusterIP
    servicePortHttp: 8080
    servicePortHttps: 8443

  extraArgs:
    - --insecure

repoServer:
  image:
    repository: ghcr.io/squallium/kubernetes-at-home/helm-secrets-argocd-repo-server
    tag: v3.1.5-helm-secrets-4.6.10
    imagePullPolicy: Always
  volumes:
    - configMap:
        name: cmp-plugin
      name: cmp-plugin
  extraContainers:
    - name: avp
      command: [ /var/run/argocd/argocd-cmp-server ]
      image: ghcr.io/squallium/kubernetes-at-home/avp-sidecar:1.18.1
      securityContext:
        runAsNonRoot: true
        runAsUser: 999
      volumeMounts:
        - mountPath: /var/run/argocd
          name: var-files
        - mountPath: /home/argocd/cmp-server/plugins
          name: plugins
        - mountPath: /tmp
          name: tmp

        # Register plugins into sidecar
        - mountPath: /home/argocd/cmp-server/config/plugin.yaml
          subPath: avp.yaml
          name: cmp-plugin
  env:
    - name: VAULT_ADDR
      value: "http://vault.vault.svc.cluster.local:8200"
    # helm secrets configuration
    - name: VAULT_NAMESPACE
      value: "vault"
    - name: VAULT_AUTH_METHOD
      value: "approle"
    - name: VAULT_ROLE_ID
      value: 0370b1d1-46ce-5239-dfbd-66f738d95a7c
    - name: VAULT_SECRET_ID
      valueFrom:
        secretKeyRef:
          name: vault-approle-secret
          key: secret-id
    # avp configuration
    - name: AVP_TYPE
      value: "vault"
    - name: AVP_AUTH_TYPE
      value: "approle"
    - name: AVP_ROLE_ID
      value: 0370b1d1-46ce-5239-dfbd-66f738d95a7c
    - name: AVP_SECRET_ID
      valueFrom:
        secretKeyRef:
          name: vault-approle-secret
          key: secret-id

configs:
  params:
    server.insecure: true  # Allow HTTP access without TLS (We'll enable HTTPS later)

  cm:
    admin.enabled: true
    url: http://argocd.internal
    exec.enabled: true
    helm.valuesFileSchemes: >-
      secrets+gpg-import, secrets+gpg-import-kubernetes,
      secrets+age-import, secrets+age-import-kubernetes,
      secrets,secrets+literal,
      https

dex:
  enabled: false  # Deactivate SSO/OAuth (we'll enable it later)
